repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        args: [--target-version, py313]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
